name: web_insets
description: Flutter web package for browser insets
version: 0.1.0
homepage: "https://github.com/AndX2/web_insets"
repository: "https://github.com/AndX2/web_insets"

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

  js: ^0.6.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
